CREATE TABLE `advert` (
   `data_item_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
   `xside` double DEFAULT NULL,
   `yside` double DEFAULT NULL,
   `accurate_floor` int(11) DEFAULT NULL,
   `additional_information` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `all_floor` int(11) DEFAULT NULL,
   `also_for_student` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `approach_road` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `condition_of_property` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `currency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `data_tracking_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `date_build` datetime DEFAULT NULL,
   `date_of_availability` datetime DEFAULT NULL,
   `dealer_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `deposit` double DEFAULT NULL,
   `deposite_curency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `desc_advert` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `details` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `district` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `equipment` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `fence` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `generate_advert_dt` datetime DEFAULT NULL,
   `heating` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `kind_of_plot` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `kind_of_transaction` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `level_finishing_building` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link3d_view` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link_development_plan` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link_film` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link_to_ad` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link_to_ad_image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `link_virtual_walking` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `living_area` double DEFAULT NULL,
   `location` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `neighbourhood` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `number_of_rooms` int(11) DEFAULT NULL,
   `offer_item_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `period_of_peyment` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `price` double DEFAULT NULL,
   `price_for_period_of_payment` double DEFAULT NULL,
   `price_per_metre` double DEFAULT NULL,
   `property_number` int(11) DEFAULT NULL,
   `property_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `security` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `street` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `type_of_building_material` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `type_of_development` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `type_of_window` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `unity_area` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   `utilities` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
   PRIMARY KEY (`data_item_id`)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci